name: map_box_geocoder
description: wrapper around map box geocoder api
version: 0.0.1
homepage: https://github.com/cedvdb/map_box_geocoding

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  path: ^1.8.0
  http: ^0.13.4

dev_dependencies:
  lints: ^1.0.0
  test: any
